add_executable (diametercodec-benchmark main.cpp)
add_library(ert_logger STATIC IMPORTED)
set_property(TARGET ert_logger PROPERTY IMPORTED_LOCATION /usr/local/lib/ert/libert_logger.a)
target_compile_definitions(diametercodec-benchmark PRIVATE BENCHMARK_BUILD_TYPE="${CMAKE_BUILD_TYPE}")
target_link_libraries(diametercodec-benchmark ${ERT_DIAMETERCODEC_TARGET_NAME} ert_logger)
